name: 'Setup Shopware'
description: 'Install Shopware'
inputs:
  shopware-version:
    description: 'Shopware Version to use'
    required: true
    default: 'v6.5.3.2'
  php-version:
    description: 'PHP Version to use'
    required: true
    default: '8.1'
runs:
  using: "composite"
  steps:
    - name: Clone Shopware
      uses: actions/checkout@v3
      with:
        repository: "shopware/platform"
        ref: ${{ inputs.shopware-version }}

    - name: Remove vendor-bin
      shell: bash
      run: rm -rf vendor-bin
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
    
    - name: Start MySQL
      shell: bash
      run: |
        sudo mv /var/lib/mysql /var/lib/mysql-old
        sudo mkdir /var/lib/mysql
        sudo mount -t tmpfs tmpfs /var/lib/mysql -o size=1G
        sudo -u mysql mysqld --datadir=/var/lib/mysql --default-time-zone=SYSTEM --initialize-insecure
        sudo systemctl start mysql

    - name: Setup Shopware Environment Variables
      shell: bash
      run: |
        echo "APP_ENV=test" >> "$GITHUB_ENV"
        echo "APP_URL=http://localhost:8000" >> "$GITHUB_ENV"
        echo "DATABASE_URL=mysql://root@localhost/shopware" >> "$GITHUB_ENV"

    - name: Retrieve the cached "vendor" directory (if present)
      uses: actions/cache@v3
      id: composer-cache
      with:
        path: vendor
        key: ${{ runner.os }}-shopware-setup-composer-${{ inputs.shopware-version }}-${{ inputs.php-version }}
    
    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      shell: bash
      run: composer install
