name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Flex Project
        run: |
                touch .env
                mkdir -p custom/plugins custom/static-plugins
                cat > composer.json << EOF
                  {
                    "name": "shopware/production",
                    "license": "MIT",
                    "type": "project",
                    "require": {
                        "composer-runtime-api": "^2.0",
                        "shopware/administration": "~6.5.0",
                        "shopware/core": "~6.5.0",
                        "shopware/elasticsearch": "~6.5.0",
                        "shopware/storefront": "~6.5.0",
                        "symfony/flex": "~2",
                        "symfony/runtime": "^5.0|^6.0"
                    },
                    "repositories": [
                        {
                            "type": "path",
                            "url": "custom/plugins/*",
                            "options": {
                                "symlink": true
                            }
                        },
                        {
                            "type": "path",
                            "url": "custom/plugins/*/packages/*",
                            "options": {
                                "symlink": true
                            }
                        },
                        {
                            "type": "path",
                            "url": "custom/static-plugins/*",
                            "options": {
                                "symlink": true
                            }
                        }
                    ],
                    "prefer-stable": true,
                    "config": {
                        "allow-plugins": {
                            "symfony/flex": true,
                            "symfony/runtime": true
                        },
                        "optimize-autoloader": true,
                        "sort-packages": true
                    },
                    "scripts": {
                        "auto-scripts": [
                        ],
                        "post-install-cmd": [
                            "@auto-scripts"
                        ],
                        "post-update-cmd": [
                            "@auto-scripts"
                        ]
                    },
                    "extra": {
                        "symfony": {
                            "allow-contrib": true,
                            "endpoint": [
                                "https://raw.githubusercontent.com/shopware/recipes/flex/main/index.json",
                                "flex://defaults"
                            ]
                        }
                    }
                }
                EOF
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      
      - name: Start MySQL
        run: |
          sudo rm -rf /var/lib/mysql
          sudo mkdir /var/lib/mysql
          sudo mount -t tmpfs tmpfs /var/lib/mysql -o size=1G
          sudo -u mysql mysqld --datadir=/var/lib/mysql --default-time-zone=SYSTEM --initialize-insecure
          sudo systemctl start mysql

      - name: Setup Shopware Environment Variables
        run: |
          echo "APP_ENV=test" >> "$GITHUB_ENV"
          echo "APP_URL=http://localhost:8000" >> "$GITHUB_ENV"
          echo "DATABASE_URL=mysql://root@localhost/shopware" >> "$GITHUB_ENV"
      
      - name: Install dependencies
        run: composer install

