name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Shopware
        uses: actions/checkout@v3
        with:
          repository: "shopware/platform"
      
      - name: Start MySQL
        run: |
          sudo rm -rf /var/lib/mysql
          sudo mkdir /var/lib/mysql
          sudo mount -t tmpfs tmpfs /var/lib/mysql -o size=1G
          sudo -u mysql mysqld --datadir=/var/lib/mysql --default-time-zone=SYSTEM --initialize-insecure
          sudo systemctl start mysql

      - name: Setup Shopware Environment Variables
        run: |
          echo "APP_ENV=test" >> "$GITHUB_ENV"
          echo "DATABASE_URL=mysql://root@localhost/shopware" >> "$GITHUB_ENV"
      
      - name: Install dependencies
        run: composer install
          
      - name: Run tests
        run: |
          ./vendor/bin/phpunit --testsuite unit
